stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - npm install --registry=https://nexus.0so.com/repository/npm/
    - npm run build-test
    - mkdir -p /home/gitlab-runner/test_b
    - rsync -az --delete  ./dist/* /home/gitlab-runner/test_b
  tags:
    - gitlab-runner-test-1
  except:
    - branches@0so_app/b

dev:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR
    - npm install --registry=https://nexus.0so.com/repository/npm/
    - npm run build-dev
    - ssh -p 1007 10.211.1.254 "mkdir -p /data/0so_web/dev/b"
    - rsync -az --delete  -e 'ssh -p 1007' ./dist/* 10.211.1.254:/data/0so_web/dev/b
  tags:
    - gitlab-runner
  only:
    - dev@0so_app/b

staging:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR
    - npm install --registry=https://nexus.0so.com/repository/npm/
    - npm run build-staging
    - ssh -p 1007 10.221.1.254 "mkdir -p /data/0so_web/staging/b"
    - rsync -az --delete  -e 'ssh -p 1007' ./dist/* 10.221.1.254:/data/0so_web/staging/b
  tags:
    - gitlab-runner
  only:
    - staging@0so_app/b

hotfix:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR
    - npm install --registry=https://nexus.0so.com/repository/npm/
    - npm run build-product
    - ssh -p 1007 10.231.1.254 "mkdir -p /data/0so_web/hotfix/b"
    - rsync -az --delete  -e 'ssh -p 1007' ./dist/* 10.231.1.254:/data/0so_web/hotfix/b
  tags:
    - gitlab-runner
  only:
    - hostfix@0so_app/b

product:
  stage: deploy
  script:
    - cd $CI_PROJECT_DIR
    - npm install --registry=https://nexus.0so.com/repository/npm/
    - npm run build-product
    - ssh -p 1007 -oStrictHostKeyChecking=no 10.254.1.254 "mkdir -p /data/0so_web/product/b"
    - rsync -az --delete  -e 'ssh -p 1007 -oStrictHostKeyChecking=no' ./dist/* 10.254.1.254:/data/0so_web/product/b
    - ssh -p 1007 -oStrictHostKeyChecking=no 10.254.2.254 "mkdir -p /data/0so_web/product/b"
    - rsync -az --delete  -e 'ssh -p 1007 -oStrictHostKeyChecking=no' ./dist/* 10.254.2.254:/data/0so_web/product/b
  tags:
    - gitlab-runner
  only:
    refs:
      - master@0so_app/b
  when: manual
